from_latest_tag = true
ignore_merge_commits = true
disable_changelog = true
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"

[git_hooks]

[commit_types]
feat = { changelog_title = "➕ Additional features" }
fix = { changelog_title = "🪲 Fixes" }
chore = { changelog_title = "🧹 Maintenance" }
docs = { changelog_title = "📚 Documentation" }
style = { changelog_title = "🎨 Code style" }
refactor = { changelog_title = "🔨 Refactoring" }
perf = { changelog_title = "⚡ Performance" }

[changelog]
template = "remote"
remote = "github.com"
owner = "mpecan"
repository = "test-semver"
authors = []

[bump_profiles]

[packages]
