from_latest_tag = true
ignore_merge_commits = true
disable_changelog = false
skip_ci = "[skip ci]"
skip_untracked = false
tag_prefix = "v"

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
