name: Version bump

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
  workflow_dispatch:

permissions:
  actions: read
  contents: write

jobs:
  perform-patch-bump:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'bump:patch')) }}
    uses: ./.github/workflows/create_release.yml
    with:
      bump_type: patch
    secrets: inherit
  perform-minor-bump:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'bump:minor')) }}
    uses: ./.github/workflows/create_release.yml
    with:
      bump_type: minor
    secrets: inherit
  perform-major-bump:
    if: ${{ (github.event.pull_request.merged == true) && (contains(github.event.pull_request.labels.*.name, 'bump:major')) }}
    uses: ./.github/workflows/create_release.yml
    with:
      bump_type: major
    secrets: inherit