name: Run on Merge action

on:
  workflow_call:
    inputs:
      bump_type:
        required: true
        type: string
        description: 'The version to release'
    
permissions:
  actions: read
  contents: write

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        with:
          check: false
          git-user: 'Cog Bot'
          git-user-email: 'cog@pecan.si'

      - name: Bump version
        id: release
        run: |
          echo "Bumping version: ${{ inputs.bump_type }}"
          cog bump --${{ inputs.bump_type }} || exit 1
          VERSION="$(git describe --tags "$(git rev-list --tags --max-count=1)")"
          echo ::set-output name=version::"$VERSION"
          git reset HEAD~ --hard

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v2
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}