name: Run on Merge action

on:
  workflow_call:
    inputs:
      bump_type:
        required: true
        type: string
        description: 'The version to release'
    
permissions:
  actions: read
  contents: write

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: "875378"
          private-key: ${{ secrets.PRIVATE_KEY }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Semver release
        uses: nagyben/cocogitto-action@89c252ef93175651731db20948e676dc58faed53
        with:
          check: false
          git-user: 'Cog Bot'
          git-user-email: 'cog@pecan.si'

      - name: Bump version
        id: release
        run: |
          echo "Bumping version: ${{ inputs.bump_type }}"
          cog bump --${{ inputs.bump_type }} --disable-bump-commit || exit 1
          VERSION="$(git describe --tags "$(git rev-list --tags --max-count=1)")"
          echo ::set-output name=version::"$VERSION"



      - name: Write version to file, commit and push to repository
        id: write-version
        run: |
          echo ${{ steps.release.outputs.version }} > VERSION.md
          git config --global user.name "PushToProtectedBranch"
          git config --global user.email "version@pecan.si"
          git add VERSION.md
          git commit -m "chore(version): Bump version to ${{ steps.release.outputs.version }}"
          git push

      - name: Generate Changelog
        run: cog changelog --at ${{ steps.release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - name: Upload github release
        uses: softprops/action-gh-release@v2
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.release.outputs.version }}