name: Run on Merge action

on:
  push:
    branches: ["main"]

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
        - name: Semver release
          uses: cocogitto/cocogitto-action@v3
          with:
            release: true
            git-user: 'Cog Bot'
            git-user-email: 'cog@pecan.si'