name: Run on Merge action

on:
  push:
    branches: ["main"]

jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        with:
          release: true
          check: false
          git-user: 'Cog Bot'
          git-user-email: 'cog@pecan.si'